name: Create Azure Function App

on:
  workflow_dispatch:
    inputs:
      functionAppName:
        description: 'Name of the Function App to create'
        required: true
        type: string
     
jobs:
  create-function-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Register Microsoft.Web provider
        run: |
             echo "Registering Microsoft.Web resource provider..."
             az provider register --namespace Microsoft.Web


      - name: Create Azure Function App
        run: |
          echo "Creating Function App named: safetychain-test1"
          az functionapp create \
            --resource-group testapp \
            --consumption-plan-location eastus \
            --runtime python \
            --functions-version 4 \
            --storage-account storagefunction1 \
            --os-type Linux

          echo "Function App created successfully!"
